In [4]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [2]:
# data path
dpath = "/content/drive/MyDrive/aidart/"

In [15]:
df_train = pd.read_csv(dpath + "train.csv")
df_test = pd.read_csv(dpath + "test.csv")

In [16]:
df_train.head()

,id,bank_months_count,branch_application_count_8weeks,credit_risk_score,current_address_months_count,customer_age,date_of_birth_distinct_emails_4w,days_since_request,device_distinct_emails_8w,device_os,...,phone_mobile_valid,prev_address_months_count,requested_credit_limit,session_length_in_minutes,source,velocity_24h,velocity_4w,velocity_6h,zip_count_4w,fraud
0,0,6.0,17.0,123,194.0,30,6,0.01,1.0,windows,...,True,NaN,200.0,4.4,INTERNET,4427.34,5459.48,6941.09,1056,0
1,1,10.0,0.0,43,12.0,20,15,0.01,1.0,linux,...,True,28.0,500.0,6.2,INTERNET,5393.91,6632.77,7743.25,1839,0
2,2,NaN,1.0,-3,107.0,30,10,0.01,1.0,linux,...,False,NaN,200.0,4.2,INTERNET,3088.89,3074.85,3449.30,2184,0
3,3,21.0,32.0,37,38.0,30,6,0.02,1.0,linux,...,True,NaN,200.0,18.4,INTERNET,3661.14,5594.04,6210.46,1107,0
4,4,NaN,0.0,62,66.0,20,12,24.00,1.0,other,...,True,NaN,200.0,3.8,TELEAPP,4142.93,4790.72,2697.17,723,0

In [17]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700000 entries, 0 to 699999
Data columns (total 33 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   id                                700000 non-null  int64
 1   bank_months_count                 522399 non-null  float64
 2   branch_application_count_8weeks   700000 non-null  float64
 3   credit_risk_score                 700000 non-null  int64
 4   current_address_months_count      697024 non-null  float64
 5   customer_age                      700000 non-null  int64
 6   date_of_birth_distinct_emails_4w  700000 non-null  int64
 7   days_since_request                700000 non-null  float64
 8   device_distinct_emails_8w         699750 non-null  float64
 9   device_os                         700000 non-null  object
 10  device_previously_fraudulent      700000 non-null  float64
 11  email_is_free                     700000 non-null  bool
 12  employment_status                 700000 non-null  object
 13  foreign_request                   700000 non-null  bool
 14  has_other_cards                   700000 non-null  bool
 15  housing_status                    700000 non-null  object
 16  income                            700000 non-null  float64
 17  initial_transfer_amount           180350 non-null  float64
 18  keep_alive_session                700000 non-null  bool
 19  month                             700000 non-null  int64
 20  name_email_similarity             700000 non-null  float64
 21  payment_type                      700000 non-null  object
 22  phone_home_valid                  700000 non-null  bool
 23  phone_mobile_valid                700000 non-null  bool
 24  prev_address_months_count         201004 non-null  float64
 25  requested_credit_limit            700000 non-null  float64
 26  session_length_in_minutes         698586 non-null  float64
 27  source                            700000 non-null  object
 28  velocity_24h                      700000 non-null  float64
 29  velocity_4w                       700000 non-null  float64
 30  velocity_6h                       700000 non-null  float64
 31  zip_count_4w                      700000 non-null  int64
 32  fraud                             700000 non-null  int64
dtypes: bool(6), float64(15), int64(7), object(5)
memory usage: 148.2+ MB

In [18]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 32 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   id                                300000 non-null  int64
 1   bank_months_count                 223966 non-null  float64
 2   branch_application_count_8weeks   300000 non-null  float64
 3   credit_risk_score                 300000 non-null  int64
 4   current_address_months_count      298722 non-null  float64
 5   customer_age                      300000 non-null  int64
 6   date_of_birth_distinct_emails_4w  300000 non-null  int64
 7   days_since_request                300000 non-null  float64
 8   device_distinct_emails_8w         299891 non-null  float64
 9   device_os                         300000 non-null  object
 10  device_previously_fraudulent      300000 non-null  float64
 11  email_is_free                     300000 non-null  bool
 12  employment_status                 300000 non-null  object
 13  foreign_request                   300000 non-null  bool
 14  has_other_cards                   300000 non-null  bool
 15  housing_status                    300000 non-null  object
 16  income                            300000 non-null  float64
 17  initial_transfer_amount           77127 non-null   float64
 18  keep_alive_session                300000 non-null  bool
 19  month                             300000 non-null  int64
 20  name_email_similarity             300000 non-null  float64
 21  payment_type                      300000 non-null  object
 22  phone_home_valid                  300000 non-null  bool
 23  phone_mobile_valid                300000 non-null  bool
 24  prev_address_months_count         86076 non-null   float64
 25  requested_credit_limit            300000 non-null  float64
 26  session_length_in_minutes         299399 non-null  float64
 27  source                            300000 non-null  object
 28  velocity_24h                      300000 non-null  float64
 29  velocity_4w                       300000 non-null  float64
 30  velocity_6h                       300000 non-null  float64
 31  zip_count_4w                      300000 non-null  int64
dtypes: bool(6), float64(15), int64(6), object(5)
memory usage: 61.2+ MB

In [19]:
print(df_train.columns)
print(df_test.columns)

Index(['id', 'bank_months_count', 'branch_application_count_8weeks',
       'credit_risk_score', 'current_address_months_count', 'customer_age',
       'date_of_birth_distinct_emails_4w', 'days_since_request',
       'device_distinct_emails_8w', 'device_os',
       'device_previously_fraudulent', 'email_is_free', 'employment_status',
       'foreign_request', 'has_other_cards', 'housing_status', 'income',
       'initial_transfer_amount', 'keep_alive_session', 'month',
       'name_email_similarity', 'payment_type', 'phone_home_valid',
       'phone_mobile_valid', 'prev_address_months_count',
       'requested_credit_limit', 'session_length_in_minutes', 'source',
       'velocity_24h', 'velocity_4w', 'velocity_6h', 'zip_count_4w', 'fraud'],
      dtype='object')
Index(['id', 'bank_months_count', 'branch_application_count_8weeks',
       'credit_risk_score', 'current_address_months_count', 'customer_age',
       'date_of_birth_distinct_emails_4w', 'days_since_request',
       'device_distinct_emails_8w', 'device_os',
       'device_previously_fraudulent', 'email_is_free', 'employment_status',
       'foreign_request', 'has_other_cards', 'housing_status', 'income',
       'initial_transfer_amount', 'keep_alive_session', 'month',
       'name_email_similarity', 'payment_type', 'phone_home_valid',
       'phone_mobile_valid', 'prev_address_months_count',
       'requested_credit_limit', 'session_length_in_minutes', 'source',
       'velocity_24h', 'velocity_4w', 'velocity_6h', 'zip_count_4w'],
      dtype='object')

In [20]:
print(df_train.isnull().sum())
print(df_test.isnull().sum())

id                                       0
bank_months_count                   177601
branch_application_count_8weeks          0
credit_risk_score                        0
current_address_months_count          2976
customer_age                             0
date_of_birth_distinct_emails_4w         0
days_since_request                       0
device_distinct_emails_8w              250
device_os                                0
device_previously_fraudulent             0
email_is_free                            0
employment_status                        0
foreign_request                          0
has_other_cards                          0
housing_status                           0
income                                   0
initial_transfer_amount             519650
keep_alive_session                       0
month                                    0
name_email_similarity                    0
payment_type                             0
phone_home_valid                         0
phone_mobile_valid                       0
prev_address_months_count           498996
requested_credit_limit                   0
session_length_in_minutes             1414
source                                   0
velocity_24h                             0
velocity_4w                              0
velocity_6h                              0
zip_count_4w                             0
fraud                                    0
dtype: int64
id                                       0
bank_months_count                    76034
branch_application_count_8weeks          0
credit_risk_score                        0
current_address_months_count          1278
customer_age                             0
date_of_birth_distinct_emails_4w         0
days_since_request                       0
device_distinct_emails_8w              109
device_os                                0
device_previously_fraudulent             0
email_is_free                            0
employment_status                        0
foreign_request                          0
has_other_cards                          0
housing_status                           0
income                                   0
initial_transfer_amount             222873
keep_alive_session                       0
month                                    0
name_email_similarity                    0
payment_type                             0
phone_home_valid                         0
phone_mobile_valid                       0
prev_address_months_count           213924
requested_credit_limit                   0
session_length_in_minutes              601
source                                   0
velocity_24h                             0
velocity_4w                              0
velocity_6h                              0
zip_count_4w                             0
dtype: int64

In [21]:
df_train.describe()

,id,bank_months_count,branch_application_count_8weeks,credit_risk_score,current_address_months_count,customer_age,date_of_birth_distinct_emails_4w,days_since_request,device_distinct_emails_8w,device_previously_fraudulent,...,month,name_email_similarity,prev_address_months_count,requested_credit_limit,session_length_in_minutes,velocity_24h,velocity_4w,velocity_6h,zip_count_4w,fraud
count,700000.000000,522399.000000,700000.000000,700000.000000,697024.000000,700000.000000,700000.000000,700000.000000,699750.000000,700000.0,...,700000.000000,700000.000000,201004.000000,700000.000000,698586.000000,700000.000000,700000.000000,700000.000000,700000.000000,700000.00000
mean,349999.500000,14.860216,184.425411,130.985149,86.918730,33.698871,9.502097,1.022278,1.019153,0.0,...,3.288677,0.493821,60.654295,515.683129,7.564633,4768.535676,4856.505326,5666.900116,1573.321961,0.01110
std,202072.738554,11.525612,459.681711,69.688134,88.357787,12.023708,5.033417,5.371060,0.176979,0.0,...,2.210689,0.289246,63.527730,487.416650,8.037437,1478.556133,920.225230,3009.598602,1005.793121,0.10477
min,0.000000,1.000000,0.000000,-170.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000001,6.000000,190.000000,0.000000,1324.790000,2863.780000,-170.600000,2.000000,0.00000
25%,174999.750000,1.000000,1.000000,83.000000,20.000000,20.000000,6.000000,0.010000,1.000000,0.0,...,1.000000,0.225204,25.000000,200.000000,3.100000,3594.017500,4268.360000,3438.385000,894.000000,0.00000
50%,349999.500000,15.000000,9.000000,122.000000,53.000000,30.000000,9.000000,0.020000,1.000000,0.0,...,3.000000,0.492449,34.000000,200.000000,5.100000,4748.815000,4914.260000,5318.765000,1263.000000,0.00000
75%,524999.250000,28.000000,25.000000,178.000000,130.000000,40.000000,13.000000,0.030000,1.000000,0.0,...,5.000000,0.755689,71.000000,500.000000,8.900000,5749.762500,5488.990000,7681.112500,1946.000000,0.00000
max,699999.000000,32.000000,2359.000000,389.000000,428.000000,90.000000,39.000000,78.460000,2.000000,0.0,...,7.000000,0.999999,381.000000,2100.000000,85.900000,9506.900000,6966.170000,16715.570000,6700.000000,1.00000

In [22]:
df_train.describe(include='object')

       device_os employment_status housing_status payment_type    source
count     700000            700000         700000       700000    700000
unique         5                 7              7            5         2
top        other                CA             BC           AB  INTERNET
freq      239434            511166         260399       259188    695146

### 결측치 처리

In [25]:
# 중앙값 대체
df_train['bank_months_count'].fillna(df_train['bank_months_count'].median(), inplace=True)
df_train['current_address_months_count'].fillna(df_train['current_address_months_count'].median(), inplace=True)
df_train['session_length_in_minutes'].fillna(df_train['session_length_in_minutes'].median(), inplace=True)

# 평균 대체
df_train['device_distinct_emails_8w'].fillna(df_train['device_distinct_emails_8w'].mean(), inplace=True)

# 0으로 대체
df_train['prev_address_months_count'].fillna(0, inplace=True)
df_train['initial_transfer_amount'].fillna(0, inplace=True)

<ipython-input-25-43b43018797b>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['bank_months_count'].fillna(df_train['bank_months_count'].median(), inplace=True)
<ipython-input-25-43b43018797b>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['current_address_months_count'].fillna(df_train['current_address_months_count'].median(), inplace=True)
<ipython-input-25-43b43018797b>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['session_length_in_minutes'].fillna(df_train['session_length_in_minutes'].median(), inplace=True)
<ipython-input-25-43b43018797b>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['device_distinct_emails_8w'].fillna(df_train['device_distinct_emails_8w'].mean(), inplace=True)
<ipython-input-25-43b43018797b>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['prev_address_months_count'].fillna(0, inplace=True)
<ipython-input-25-43b43018797b>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['initial_transfer_amount'].fillna(0, inplace=True)

In [26]:
print(df_train.isnull().sum())

id                                  0
bank_months_count                   0
branch_application_count_8weeks     0
credit_risk_score                   0
current_address_months_count        0
customer_age                        0
date_of_birth_distinct_emails_4w    0
days_since_request                  0
device_distinct_emails_8w           0
device_os                           0
device_previously_fraudulent        0
email_is_free                       0
employment_status                   0
foreign_request                     0
has_other_cards                     0
housing_status                      0
income                              0
initial_transfer_amount             0
keep_alive_session                  0
month                               0
name_email_similarity               0
payment_type                        0
phone_home_valid                    0
phone_mobile_valid                  0
prev_address_months_count           0
requested_credit_limit              0
session_length_in_minutes           0
source                              0
velocity_24h                        0
velocity_4w                         0
velocity_6h                         0
zip_count_4w                        0
fraud                               0
dtype: int64

### 인코딩

In [27]:
categorical_cols = df_train.select_dtypes(include=['object', 'bool']).columns.tolist()

변수명	자료형	고유값 수	예시 값	추천 인코딩 방식	이유

device_os	object	5	linux, windows 등	One-Hot	OS 간 서열 없음

employment_status	object	~6	employed, retired 등	One-Hot	명목형, 비교 불가능

housing_status	object	~6	own, rent 등	One-Hot	명목형, 의미 없음

payment_type	object	~6	card, cash 등	One-Hot	명목형

source	object	2	INTERNET, TELEAPP	Binary Encoding 또는 One-Hot	2개라면 binary 가능

email_is_free	bool	2	True / False	0/1 매핑 (그대로 사용)	이진 변수

foreign_request	bool	2	True / False	0/1 매핑 (그대로 사용)	이진 변수

has_other_cards	bool	2	True / False	0/1 매핑 (그대로 사용)	이진 변수

keep_alive_session	bool	2	True / False	0/1 매핑 (그대로 사용)	이진 변수

phone_home_valid	bool	2	True / False	0/1 매핑 (그대로 사용)	이진 변수

phone_mobile_valid	bool	2	True / False	0/1 매핑 (그대로 사용)	이진 변수

In [29]:
# 인코딩 대상 구분
one_hot_cols = ['device_os', 'employment_status', 'housing_status', 'payment_type', 'source']
binary_cols = ['email_is_free', 'foreign_request', 'has_other_cards',
               'keep_alive_session', 'phone_home_valid', 'phone_mobile_valid']

# 복사본 생성
df_encoded = df_train.copy()

# Boolean 변수 0/1 변환
df_encoded[binary_cols] = df_encoded[binary_cols].astype(int)

# One-Hot 인코딩 적용
df_encoded = pd.get_dummies(df_encoded, columns=one_hot_cols, drop_first=False)

# 결과 미리보기
print(df_encoded.head())

   id  bank_months_count  branch_application_count_8weeks  credit_risk_score  \
0   0                6.0                             17.0                123
1   1               10.0                              0.0                 43
2   2               15.0                              1.0                 -3
3   3               21.0                             32.0                 37
4   4               15.0                              0.0                 62

   current_address_months_count  customer_age  \
0                         194.0            30
1                          12.0            20
2                         107.0            30
3                          38.0            30
4                          66.0            20

   date_of_birth_distinct_emails_4w  days_since_request  \
0                                 6                0.01
1                                15                0.01
2                                10                0.01
3                                 6                0.02
4                                12               24.00

   device_distinct_emails_8w  device_previously_fraudulent  ...  \
0                        1.0                           0.0  ...
1                        1.0                           0.0  ...
2                        1.0                           0.0  ...
3                        1.0                           0.0  ...
4                        1.0                           0.0  ...

   housing_status_BE  housing_status_BF  housing_status_BG  payment_type_AA  \
0               True              False              False             True
1               True              False              False             True
2              False              False              False            False
3              False              False              False            False
4              False              False              False            False

   payment_type_AB  payment_type_AC  payment_type_AD  payment_type_AE  \
0            False            False            False            False
1            False            False            False            False
2            False             True            False            False
3             True            False            False            False
4            False             True            False            False

   source_INTERNET  source_TELEAPP
0             True           False
1             True           False
2             True           False
3             True           False
4            False            True

[5 rows x 54 columns]